version : 2

sources :
  - name: raw data #arbitrary, people put the source name (google analytics, crm, etc)
    description: "raw data sources for NYT taxi rides"
    database: taxi_rides_ny #name of the duckdb file
    schema: prod #use settings defined in the profiles.yml
    tables: #generate the required tables based on duckdb file
      - name: yellow_tripdata #remember in ingest.py we name the table using this format
      - name: green_tripdata